using System;
using System.Collections.Generic;
using System.IO;
using Avalonia.Controls;
using Avalonia.Interactivity;
using Avalonia.Media.Imaging;
using PlantCare.Data;
using PlantCare.Models;
using PlantCare.Services;
using PlantCare.Utils;

namespace PlantCare
{
    public partial class MainWindow : Window
    {
        private readonly PlantService _service;
        private List<Plant> _plants = new();
        private Plant? _currentPlant;
        private bool _isNew = true;

        public MainWindow()
        {
            InitializeComponent();

            var dataPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "plants.json");
            var repo = new FilePlantRepository(dataPath);
            _service = new PlantService(repo);

            // Hook events using named controls generated by Avalonia
            PlantList.SelectionChanged += PlantList_SelectionChanged;
            NewPlantButton.Click += NewPlantButton_Click;
            SavePlantButton.Click += SavePlantButton_Click;
            DeletePlantButton.Click += DeletePlantButton_Click;
            BrowseImageButton.Click += BrowseImageButton_Click;
            AddLogButton.Click += AddLogButton_Click;
            TaskDatePicker.SelectedDateChanged += TaskDatePicker_SelectedDateChanged;
            ExportCsvButton.Click += ExportCsvButton_Click;

            // Defaults (DatePicker.SelectedDate is DateTime?)
            TaskDatePicker.SelectedDate = DateTime.Now;
            LastWateredPicker.SelectedDate = DateTime.Now;
            LastFertilizedPicker.SelectedDate = DateTime.Now;

            LoadPlants();
            UpdateTasksForDate(DateTime.Today);
        }

        private void LoadPlants()
        {
            _plants = _service.GetAllPlants();
            PlantList.ItemsSource = _plants;
            PlantList.SelectedItem = _plants.Count > 0 ? _plants[0] : null;

            if (_plants.Count == 0)
                ClearDetails();
        }

        private void PlantList_SelectionChanged(object? sender, SelectionChangedEventArgs e)
        {
            if (PlantList.SelectedItem is Plant plant)
            {
                _currentPlant = plant;
                _isNew = false;
                PopulateDetails(plant);
            }
        }

        private void PopulateDetails(Plant plant)
        {
            NameTextBox.Text = plant.Name;
            SpeciesTextBox.Text = plant.Species;
            LocationTextBox.Text = plant.Location;
            WaterDaysTextBox.Text = plant.WateringIntervalDays.ToString();
            FertilizeDaysTextBox.Text = plant.FertilizingIntervalDays.ToString();

            LastWateredPicker.SelectedDate =
                plant.LastWatered == DateTime.MinValue ? DateTime.Now : plant.LastWatered;

            LastFertilizedPicker.SelectedDate =
                plant.LastFertilized == DateTime.MinValue ? DateTime.Now : plant.LastFertilized;

            ImagePathTextBox.Text = plant.ImagePath ?? "";
            LoadImage(plant.ImagePath);

            LogListBox.ItemsSource = plant.Logs ?? new List<PlantLogEntry>();

            if (plant.WateringIntervalDays > 0 && plant.LastWatered != DateTime.MinValue)
            {
                var next = plant.LastWatered.Date.AddDays(plant.WateringIntervalDays);
                NextWaterLabel.Text = $"Next watering: {next:d}";
            }
            else
            {
                NextWaterLabel.Text = "Next watering: -";
            }

            if (plant.FertilizingIntervalDays > 0 && plant.LastFertilized != DateTime.MinValue)
            {
                var next = plant.LastFertilized.Date.AddDays(plant.FertilizingIntervalDays);
                NextFertilizeLabel.Text = $"Next fertilizing: {next:d}";
            }
            else
            {
                NextFertilizeLabel.Text = "Next fertilizing: -";
            }
        }

        private void ClearDetails()
        {
            _currentPlant = null;
            _isNew = true;

            NameTextBox.Text = "";
            SpeciesTextBox.Text = "";
            LocationTextBox.Text = "";
            WaterDaysTextBox.Text = "";
            FertilizeDaysTextBox.Text = "";
            LastWateredPicker.SelectedDate = DateTime.Now;
            LastFertilizedPicker.SelectedDate = DateTime.Now;
            ImagePathTextBox.Text = "";
            PlantImage.Source = null;
            LogListBox.ItemsSource = null;
            NextWaterLabel.Text = "Next watering: -";
            NextFertilizeLabel.Text = "Next fertilizing: -";
        }

        private async void BrowseImageButton_Click(object? sender, RoutedEventArgs e)
        {
            // Using obsolete OpenFileDialog is fine for now – quick and simple
            var ofd = new OpenFileDialog
            {
                Title = "Select plant image",
                AllowMultiple = false,
                Filters =
                {
                    new FileDialogFilter { Name="Images", Extensions = { "png","jpg","jpeg","bmp","gif" } }
                }
            };

            var result = await ofd.ShowAsync(this);
            if (result != null && result.Length > 0)
            {
                ImagePathTextBox.Text = result[0];
                LoadImage(result[0]);
            }
        }

        private void LoadImage(string? path)
        {
            PlantImage.Source = null;
            if (string.IsNullOrWhiteSpace(path)) return;
            try
            {
                if (File.Exists(path))
                    PlantImage.Source = new Bitmap(path);
            }
            catch (Exception ex)
            {
                Logger.Log(ex);
            }
        }

        private void NewPlantButton_Click(object? sender, RoutedEventArgs e)
        {
            ClearDetails();
        }
        private async void SavePlantButton_Click(object? sender, RoutedEventArgs e)
{
    try
    {
        // INVALID INPUT HANDLING – throws an exception purposely
        if (!int.TryParse(WaterDaysTextBox.Text?.Trim(), out var waterDays))
            throw new FormatException("Watering interval must be a number.");

        if (!int.TryParse(FertilizeDaysTextBox.Text?.Trim(), out var fertDays))
            throw new FormatException("Fertilizing interval must be a number.");

        if (string.IsNullOrWhiteSpace(NameTextBox.Text))
            throw new FormatException("Plant name cannot be empty.");

        var plant = _currentPlant ?? new Plant
        {
            Logs = new List<PlantLogEntry>()
        };

        plant.Name = NameTextBox.Text?.Trim() ?? "";
        plant.Species = SpeciesTextBox.Text?.Trim() ?? "";
        plant.Location = LocationTextBox.Text?.Trim() ?? "";
        plant.WateringIntervalDays = waterDays;
        plant.FertilizingIntervalDays = fertDays;
        plant.LastWatered = (LastWateredPicker.SelectedDate ?? DateTime.Now).Date;
        plant.LastFertilized = (LastFertilizedPicker.SelectedDate ?? DateTime.Now).Date;
        plant.ImagePath = ImagePathTextBox.Text?.Trim() ?? "";

        if (_isNew || _currentPlant == null)
        {
            _service.AddPlant(plant);
        }
        else
        {
            plant.Id = _currentPlant.Id;
            plant.Logs = _currentPlant.Logs;
            _service.UpdatePlant(plant);
        }

        LoadPlants();
        StatusLabel.Text = "Plant saved successfully.";
    }
    catch (FormatException ex) // Catches invalid user input errors
    {
        StatusLabel.Text = ex.Message;
        Logger.Log(ex);
    }
    catch (Exception ex) // Catches unexpected technical errors
    {
        Logger.Log(ex);
        StatusLabel.Text = "Unexpected error while saving.";
    }
}


private async void DeletePlantButton_Click(object? sender, RoutedEventArgs e)
{
    if (_currentPlant == null)
    {
        await ShowMessage("No plant selected to delete.");
        return;
    }

    // 2. protect Snake Plant from deletion
    if (string.Equals(_currentPlant.Name, "Snake Plant", StringComparison.OrdinalIgnoreCase))
    {
        await ShowMessage("Default plant 'Snake Plant' cannot be deleted!");
        return;
    }

    bool confirmed = await Confirm($"Delete plant '{_currentPlant.Name}'?");
    if (!confirmed) return;

    try
    {
        _service.DeletePlant(_currentPlant.Id);

        // reload list after delete
        LoadPlants();

        // if there are still plants, select the first one
        if (_plants.Count > 0)
        {
            _currentPlant = _plants[0];
            PlantList.SelectedItem = _currentPlant;
            PopulateDetails(_currentPlant);
        }
        else
        {
            ClearDetails();
        }

        StatusLabel.Text = "Plant deleted.";
    }
    catch (Exception ex)
    {
        Logger.Log(ex);
        await ShowMessage("Error deleting plant: " + ex.Message);
    }
}
       


      private async void AddLogButton_Click(object? sender, RoutedEventArgs e)
{
    if (_currentPlant == null)
    {
        await ShowMessage("Select a plant first.");
        return;
    }

    var note = LogNoteTextBox.Text?.Trim();
    if (string.IsNullOrWhiteSpace(note))
    {
        await ShowMessage("Enter a note for the log.");
        return;
    }

    try
    {
        var log = new PlantLogEntry
        {
            Date = DateTime.Now,
            Note = note
        };

        // Update data via service (this saves to JSON too)
        _service.AddLogEntry(_currentPlant.Id, log);

        // Reload plants from service so we get updated Logs
        _plants = _service.GetAllPlants();
        _currentPlant = _plants.Find(p => p.Id == _currentPlant.Id);

        // Refresh list and logs in UI
        PlantList.ItemsSource = null;
        PlantList.ItemsSource = _plants;
        PlantList.SelectedItem = _currentPlant;

        LogListBox.ItemsSource = null;
        LogListBox.ItemsSource = _currentPlant?.Logs;

        LogNoteTextBox.Text = "";
        StatusLabel.Text = "Log added.";
    }
    catch (Exception ex)
    {
        Logger.Log(ex);
        await ShowMessage("Error adding log: " + ex.Message);
    }
}


           

       

        private void TaskDatePicker_SelectedDateChanged(object? sender, SelectionChangedEventArgs e)
        {
            var date = (TaskDatePicker.SelectedDate ?? DateTime.Now).Date;
            UpdateTasksForDate(date);
        }

        private void UpdateTasksForDate(DateTime date)
        {
            try
            {
                var tasks = _service.GetTasksForDate(date);
                TaskListBox.ItemsSource = tasks;
            }
            catch (Exception ex)
            {
                Logger.Log(ex);
            }
        }

           private System.Threading.Tasks.Task ShowMessage(string text)
        {
            // just update status bar text
            StatusLabel.Text = text;
            return System.Threading.Tasks.Task.CompletedTask;
        }
        

        private System.Threading.Tasks.Task<bool> Confirm(string text)
        {
            // For simplicity (and to avoid crashes), auto-confirm
            return System.Threading.Tasks.Task.FromResult(true);
        }

        private async void ExportCsvButton_Click(object? sender, RoutedEventArgs e)
{
    try
    {
        var csvPath = Path.Combine(Environment.CurrentDirectory, "plants.csv");
        _service.ExportToCsv(csvPath);
        await ShowMessage($"Exported to plants.csv in project folder.");
    }
    catch (Exception ex)
    {
        Logger.Log(ex);
        await ShowMessage("Error exporting CSV: " + ex.Message);
    }
}

    }
}
